"""empty message

Revision ID: aac668a8ed85
Revises: 
Create Date: 2018-05-22 17:08:02.238255

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aac668a8ed85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('shift', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('citizenships',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('parents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('phone', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('passport', sa.String(length=255), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('home_phone', sa.String(length=255), nullable=True),
                    sa.Column('vk_link', sa.String(length=255), nullable=True),
                    sa.Column('notification_types', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('passport')
                    )
    op.create_table('schools',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('sections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('system_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('details_table_name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('day_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('day', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('candidate_id', 'day')
                    )
    op.create_table('section_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('candidate_id', 'section_id')
                    )
    op.create_table('system_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(length=255), nullable=False),
                    sa.Column('system_role_id', sa.Integer(), nullable=False),
                    sa.Column('last_seen', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['system_role_id'], ['system_roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login'),
                    sa.UniqueConstraint('password_hash')
                    )
    op.create_table('masters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system_user_id')
                    )
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_type', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.Text(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('send_time', sa.DateTime(), nullable=False),
                    sa.Column('receivers', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['sender_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notifications_receiver_type'), 'notifications', ['receiver_type'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('birth_place', sa.String(length=255), nullable=False),
                    sa.Column('registration_place', sa.String(length=255), nullable=False),
                    sa.Column('actual_address', sa.String(length=255), nullable=False),
                    sa.Column('additional_info', sa.Text(), nullable=True),
                    sa.Column('known_from', sa.Text(), nullable=True),
                    sa.Column('school_id', sa.Integer(), nullable=False),
                    sa.Column('citizenship_id', sa.Integer(), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['citizenship_id'], ['citizenships.id'], ),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system_user_id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system_user_id')
                    )
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('start_month', sa.Integer(), nullable=False),
                    sa.Column('end_month', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_groups_end_month'), 'groups', ['end_month'], unique=False)
    op.create_index(op.f('ix_groups_start_month'), 'groups', ['start_month'], unique=False)
    op.create_table('parent_of_students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('is_mother', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('student_id', 'is_mother'),
                    sa.UniqueConstraint('student_id', 'parent_id'),
                    sa.UniqueConstraint('student_id', 'parent_id', 'is_mother')
                    )
    op.create_table('lessons',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_lessons_date'), 'lessons', ['date'], unique=False)
    op.create_index(op.f('ix_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_table('student_in_groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('discount', sa.Integer(), nullable=False),
                    sa.Column('enter_month', sa.Integer(), nullable=False),
                    sa.Column('exit_month', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('student_id', 'group_id')
                    )
    op.create_index(op.f('ix_student_in_groups_enter_month'), 'student_in_groups', ['enter_month'], unique=False)
    op.create_index(op.f('ix_student_in_groups_exit_month'), 'student_in_groups', ['exit_month'], unique=False)
    op.create_index(op.f('ix_student_in_groups_group_id'), 'student_in_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_student_in_groups_student_id'), 'student_in_groups', ['student_id'], unique=False)
    op.create_table('attendings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('was', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('student_id', 'lesson_id')
                    )
    op.create_index(op.f('ix_attendings_lesson_id'), 'attendings', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_attendings_student_id'), 'attendings', ['student_id'], unique=False)
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_in_group_id', sa.Integer(), nullable=False),
                    sa.Column('month', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.Column('cash', sa.Boolean(), nullable=False),
                    sa.Column('confirmed', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['student_in_group_id'], ['student_in_groups.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('student_in_group_id', 'month')
                    )
    op.create_index(op.f('ix_payments_month'), 'payments', ['month'], unique=False)
    op.create_index(op.f('ix_payments_student_in_group_id'), 'payments', ['student_in_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_in_group_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_month'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_attendings_student_id'), table_name='attendings')
    op.drop_index(op.f('ix_attendings_lesson_id'), table_name='attendings')
    op.drop_table('attendings')
    op.drop_index(op.f('ix_student_in_groups_student_id'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_group_id'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_exit_month'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_enter_month'), table_name='student_in_groups')
    op.drop_table('student_in_groups')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_date'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('parent_of_students')
    op.drop_index(op.f('ix_groups_start_month'), table_name='groups')
    op.drop_index(op.f('ix_groups_end_month'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('masters')
    op.drop_table('system_users')
    op.drop_table('section_preferences')
    op.drop_table('day_preferences')
    op.drop_table('system_roles')
    op.drop_table('sections')
    op.drop_table('schools')
    op.drop_table('parents')
    op.drop_table('citizenships')
    op.drop_table('candidates')
    # ### end Alembic commands ###
