"""empty message

Revision ID: 1b3612524fe2
Revises: 8a0de7bb4557
Create Date: 2018-01-08 18:00:25.772078

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b3612524fe2'
down_revision = '8a0de7bb4557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizenships',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('parents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('phone', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('passport', sa.String(length=255), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('home_phone', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('passport')
                    )
    op.create_table('schools',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('birth_place', sa.String(length=255), nullable=False),
                    sa.Column('registration_place', sa.String(length=255), nullable=False),
                    sa.Column('actual_address', sa.String(length=255), nullable=False),
                    sa.Column('additional_info', sa.Text(), nullable=True),
                    sa.Column('known_from', sa.Text(), nullable=True),
                    sa.Column('school_id', sa.Integer(), nullable=False),
                    sa.Column('mother_id', sa.Integer(), nullable=True),
                    sa.Column('father_id', sa.Integer(), nullable=True),
                    sa.Column('citizenship_id', sa.Integer(), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['citizenship_id'], ['citizenships.id'], ),
                    sa.ForeignKeyConstraint(['father_id'], ['parents.id'], ),
                    sa.ForeignKeyConstraint(['mother_id'], ['parents.id'], ),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('parents')
    op.drop_table('citizenships')
    # ### end Alembic commands ###
