"""empty message

Revision ID: 2fa4ca1b6a60
Revises: 8e958bdc7bca
Create Date: 2018-01-11 22:19:18.569482

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2fa4ca1b6a60'
down_revision = '8e958bdc7bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_of_students', sa.Column('is_mother', sa.Boolean(), nullable=False))
    op.drop_constraint('parent_of_students_student_id_parent_id_key', 'parent_of_students', type_='unique')
    op.create_unique_constraint(None, 'parent_of_students', ['student_id', 'parent_id', 'is_mother'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_of_students', type_='unique')
    op.create_unique_constraint('parent_of_students_student_id_parent_id_key', 'parent_of_students',
                                ['student_id', 'parent_id'])
    op.drop_column('parent_of_students', 'is_mother')
    # ### end Alembic commands ###
