"""empty message

Revision ID: 9d4ba59330fe
Revises: 7e318f1226c4
Create Date: 2018-01-22 19:20:08.313921

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9d4ba59330fe'
down_revision = '7e318f1226c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('end_month', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('start_month', sa.Integer(), nullable=True))
    op.drop_column('groups', 'start_year')
    op.alter_column('student_in_groups', 'discount',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_in_groups', 'discount',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column('groups', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('groups', 'start_month')
    op.drop_column('groups', 'end_month')
    # ### end Alembic commands ###
