"""empty message

Revision ID: 76e333d0fc95
Revises: 2fa4ca1b6a60
Create Date: 2018-01-11 22:43:41.819604

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '76e333d0fc95'
down_revision = '2fa4ca1b6a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parent_of_students', ['student_id', 'parent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_of_students', type_='unique')
    # ### end Alembic commands ###
