"""empty message

Revision ID: 00d59e452bea
Revises: 9d4ba59330fe
Create Date: 2018-01-22 19:24:26.170712

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '00d59e452bea'
down_revision = '9d4ba59330fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'end_month',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('groups', 'start_month',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'start_month',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('groups', 'end_month',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
