"""empty message

Revision ID: ff1d5128ebec
Revises: 0328aad8bd36
Create Date: 2018-06-07 11:39:01.417909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = 'ff1d5128ebec'
down_revision = '0328aad8bd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('enabled', sa.Boolean(), nullable=False, server_default=expression.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_users', 'enabled')
    # ### end Alembic commands ###
