"""empty message

Revision ID: f184033ccac0
Revises: 1b3612524fe2
Create Date: 2018-01-08 18:23:52.578900

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f184033ccac0'
down_revision = '1b3612524fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('masters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system_user_id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system_user_id')
                    )
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('lessons',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('student_in_groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('discount', sa.Integer(), nullable=True),
                    sa.Column('enter_date', sa.Date(), nullable=False),
                    sa.Column('exit_date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('attendings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('was', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_in_group_id', sa.Integer(), nullable=False),
                    sa.Column('month', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.Column('cash', sa.Boolean(), nullable=False),
                    sa.Column('confirmed', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['student_in_group_id'], ['student_in_groups.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_unique_constraint(None, 'students', ['system_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_table('payments')
    op.drop_table('attendings')
    op.drop_table('student_in_groups')
    op.drop_table('lessons')
    op.drop_table('groups')
    op.drop_table('teachers')
    op.drop_table('masters')
    op.drop_table('sections')
    # ### end Alembic commands ###
