"""empty message

Revision ID: 62861862c523
Revises: f184033ccac0
Create Date: 2018-01-08 18:48:14.621098

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '62861862c523'
down_revision = 'f184033ccac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fio', sa.String(length=255), nullable=False),
                    sa.Column('shift', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('day_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('day', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('section_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_preferences')
    op.drop_table('day_preferences')
    op.drop_table('candidates')
    # ### end Alembic commands ###
