"""empty message

Revision ID: ea3a94724a9c
Revises: ff1d5128ebec
Create Date: 2018-06-11 11:20:13.857029

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from app.models import contact_phone_student

revision = 'ea3a94724a9c'
down_revision = 'ff1d5128ebec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('contact_phone', sa.Integer(), nullable=False,
                                        server_default=str(contact_phone_student)))
    op.add_column('students', sa.Column('grade', sa.String(length=32), nullable=False, server_default='n/a'))
    op.add_column('students', sa.Column('phone', sa.String(length=255), nullable=True, server_default='n/a'))
    op.add_column('students', sa.Column('shift', sa.String(length=32), nullable=False, server_default='n/a'))
    op.add_column('teachers', sa.Column('phone', sa.String(length=255), nullable=False, server_default='n/a'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'phone')
    op.drop_column('students', 'shift')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'contact_phone')
    # ### end Alembic commands ###
