"""empty message

Revision ID: 94caeabfed70
Revises: 00d59e452bea
Create Date: 2018-01-25 11:18:27.284746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94caeabfed70'
down_revision = '00d59e452bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendings_lesson_id'), 'attendings', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_attendings_student_id'), 'attendings', ['student_id'], unique=False)
    op.create_index(op.f('ix_groups_end_month'), 'groups', ['end_month'], unique=False)
    op.create_index(op.f('ix_groups_start_month'), 'groups', ['start_month'], unique=False)
    op.create_index(op.f('ix_lessons_date'), 'lessons', ['date'], unique=False)
    op.create_index(op.f('ix_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_payments_month'), 'payments', ['month'], unique=False)
    op.create_index(op.f('ix_payments_student_in_group_id'), 'payments', ['student_in_group_id'], unique=False)
    op.create_index(op.f('ix_student_in_groups_enter_month'), 'student_in_groups', ['enter_month'], unique=False)
    op.create_index(op.f('ix_student_in_groups_exit_month'), 'student_in_groups', ['exit_month'], unique=False)
    op.create_index(op.f('ix_student_in_groups_group_id'), 'student_in_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_student_in_groups_student_id'), 'student_in_groups', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_in_groups_student_id'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_group_id'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_exit_month'), table_name='student_in_groups')
    op.drop_index(op.f('ix_student_in_groups_enter_month'), table_name='student_in_groups')
    op.drop_index(op.f('ix_payments_student_in_group_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_month'), table_name='payments')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_date'), table_name='lessons')
    op.drop_index(op.f('ix_groups_start_month'), table_name='groups')
    op.drop_index(op.f('ix_groups_end_month'), table_name='groups')
    op.drop_index(op.f('ix_attendings_student_id'), table_name='attendings')
    op.drop_index(op.f('ix_attendings_lesson_id'), table_name='attendings')
    # ### end Alembic commands ###
