"""empty message

Revision ID: e2544529f0bc
Revises: ea3a94724a9c
Create Date: 2018-06-18 12:01:11.819133

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e2544529f0bc'
down_revision = 'ea3a94724a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
