"""empty message

Revision ID: a3a1d9e90ffa
Revises: 62861862c523
Create Date: 2018-01-08 20:37:19.279018

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3a1d9e90ffa'
down_revision = '62861862c523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_of_students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('students_father_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_mother_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'mother_id')
    op.drop_column('students', 'father_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('father_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mother_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_mother_id_fkey', 'students', 'parents', ['mother_id'], ['id'])
    op.create_foreign_key('students_father_id_fkey', 'students', 'parents', ['father_id'], ['id'])
    op.drop_table('parent_of_students')
    # ### end Alembic commands ###
