"""empty message

Revision ID: 55e0d02b249a
Revises: 94caeabfed70
Create Date: 2018-05-17 16:58:24.606348

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55e0d02b249a'
down_revision = '94caeabfed70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('student_in_group_id', sa.Integer(), nullable=True),
                    sa.Column('subject', sa.Text(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('send_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['system_users.id'], ),
                    sa.ForeignKeyConstraint(['student_in_group_id'], ['student_in_groups.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_group_id'), 'notifications', ['group_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_student_in_group_id'), 'notifications', ['student_in_group_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_student_in_group_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_group_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
