"""empty message

Revision ID: a8520636b53a
Revises: 55e0d02b249a
Create Date: 2018-05-18 11:51:08.051725

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a8520636b53a'
down_revision = '55e0d02b249a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('receiver_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('notifications', sa.Column('receiver_type', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notifications_receiver_type'), 'notifications', ['receiver_type'], unique=False)
    op.drop_index('ix_notifications_group_id', table_name='notifications')
    op.drop_index('ix_notifications_student_in_group_id', table_name='notifications')
    op.drop_constraint('notifications_group_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_student_in_group_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'student_in_group_id')
    op.drop_column('notifications', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('student_in_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notifications_student_in_group_id_fkey', 'notifications', 'student_in_groups',
                          ['student_in_group_id'], ['id'])
    op.create_foreign_key('notifications_group_id_fkey', 'notifications', 'groups', ['group_id'], ['id'])
    op.create_index('ix_notifications_student_in_group_id', 'notifications', ['student_in_group_id'], unique=False)
    op.create_index('ix_notifications_group_id', 'notifications', ['group_id'], unique=False)
    op.drop_index(op.f('ix_notifications_receiver_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_column('notifications', 'receiver_type')
    op.drop_column('notifications', 'receiver_id')
    # ### end Alembic commands ###
