"""empty message

Revision ID: 574cd0dc8038
Revises: e2544529f0bc
Create Date: 2018-06-20 13:03:37.683881

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '574cd0dc8038'
down_revision = 'e2544529f0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_times',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time', sa.String(length=8), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('schedule_groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('schedule_time_id', sa.Integer(), nullable=False),
                    sa.Column('day_of_week', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['schedule_time_id'], ['schedule_times.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('schedule_time_id', 'day_of_week')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_groups')
    op.drop_table('schedule_times')
    # ### end Alembic commands ###
