"""empty message

Revision ID: 05ec8f0ec9bf
Revises: 574cd0dc8038
Create Date: 2018-07-01 12:01:05.848434

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from app.models import attending_was_not, attending_was

revision = '05ec8f0ec9bf'
down_revision = '574cd0dc8038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendings', sa.Column('state', sa.Integer(), nullable=True))
    op.execute("UPDATE attendings SET state = {} WHERE was = FALSE".format(attending_was_not))
    op.execute("UPDATE attendings SET state = {} WHERE was = TRUE".format(attending_was))
    op.alter_column('attendings', 'state',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.drop_column('attendings', 'was')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendings',
                  sa.Column('was', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='FALSE'))
    op.drop_column('attendings', 'state')
    # ### end Alembic commands ###
