"""empty message

Revision ID: 9e1c0facd25c
Revises: a8520636b53a
Create Date: 2018-05-18 13:48:38.397215

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9e1c0facd25c'
down_revision = 'a8520636b53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('receivers', sa.Text(), nullable=False, server_default='smth'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'receivers')
    # ### end Alembic commands ###
