"""empty message

Revision ID: a0d696dabd58
Revises: 303fc6ae9353
Create Date: 2018-09-18 08:17:16.259416

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a0d696dabd58'
down_revision = '303fc6ae9353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.Column('system_user_id', sa.Integer(), nullable=False),
                    sa.Column('expires', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['system_user_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
