"""empty message

Revision ID: f045df9b3228
Revises: 1cce20c5009d
Create Date: 2018-05-21 10:21:56.420144

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f045df9b3228'
down_revision = '1cce20c5009d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('notification_types', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('parents', sa.Column('vk_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'vk_id')
    op.drop_column('parents', 'notification_types')
    # ### end Alembic commands ###
