"""empty message

Revision ID: 8fccf2b07b53
Revises: f045df9b3228
Create Date: 2018-05-22 09:54:40.316389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fccf2b07b53'
down_revision = 'f045df9b3228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'vk_id', new_column_name='vk_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'vk_link', new_column_name='vk_id')
    # ### end Alembic commands ###
