"""empty message

Revision ID: 0cc7a8bc2269
Revises: d1ef5243daea
Create Date: 2018-09-23 16:48:58.329418

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from app.models import last_seen_web

revision = '0cc7a8bc2269'
down_revision = 'd1ef5243daea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('last_seen_where', sa.Integer(), nullable=False,
                                            server_default=str(last_seen_web)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_users', 'last_seen_where')
    # ### end Alembic commands ###
