"""empty message

Revision ID: f42af39ce5b6
Revises: 0cc7a8bc2269
Create Date: 2018-10-04 09:24:42.516224

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.sql import expression

revision = 'f42af39ce5b6'
down_revision = '0cc7a8bc2269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('force_ask_to_login', sa.Boolean(), nullable=False,
                                            server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_users', 'force_ask_to_login')
    # ### end Alembic commands ###
