"""empty message

Revision ID: 54ebcc304732
Revises: a7b292e8d28a
Create Date: 2018-10-04 09:35:07.265704

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.sql import expression

revision = '54ebcc304732'
down_revision = 'a7b292e8d28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('force_ask_to_login', sa.Boolean(), nullable=False,
                                            server_default=expression.false()))
    op.drop_column('system_users', 'force_ask_to_login_app')
    op.drop_column('system_users', 'force_ask_to_login_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('force_ask_to_login_site', sa.BOOLEAN(), server_default=sa.text('false'),
                                            autoincrement=False, nullable=False))
    op.add_column('system_users', sa.Column('force_ask_to_login_app', sa.BOOLEAN(), server_default=sa.text('false'),
                                            autoincrement=False, nullable=False))
    op.drop_column('system_users', 'force_ask_to_login')
    # ### end Alembic commands ###
