"""empty message

Revision ID: 53eafd1e2da4
Revises: 0f60b647eb99
Create Date: 2019-02-28 11:19:19.771784

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '53eafd1e2da4'
down_revision = '0f60b647eb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('fio', sa.String(length=255), nullable=False))
    op.drop_column('bots', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('bots', 'fio')
    # ### end Alembic commands ###
