"""empty message

Revision ID: 514c0e6b381a
Revises: 6053f9f75e68
Create Date: 2019-02-28 13:11:04.019767

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '514c0e6b381a'
down_revision = '6053f9f75e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visits',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('page', sa.String(length=255), nullable=False),
                    sa.Column('visits_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_visits')
    # ### end Alembic commands ###
