"""empty message

Revision ID: 0ab6121b7b25
Revises: 514c0e6b381a
Create Date: 2019-02-28 13:15:58.320370

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0ab6121b7b25'
down_revision = '514c0e6b381a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('page_name', sa.String(length=255), nullable=False))
    op.drop_column('page_visits', 'page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('page', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('page_visits', 'page_name')
    # ### end Alembic commands ###
