"""empty message

Revision ID: 25dd50d63a33
Revises: 0ab6121b7b25
Create Date: 2019-02-28 13:28:51.496190

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '25dd50d63a33'
down_revision = '0ab6121b7b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_page_visits_page_name'), 'page_visits', ['page_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_visits_page_name'), table_name='page_visits')
    # ### end Alembic commands ###
