"""empty message

Revision ID: 71f9514c26e6
Revises: 25dd50d63a33
Create Date: 2019-02-28 13:29:28.874147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f9514c26e6'
down_revision = '25dd50d63a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_visits_page_name', table_name='page_visits')
    op.create_index(op.f('ix_page_visits_page_name'), 'page_visits', ['page_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_visits_page_name'), table_name='page_visits')
    op.create_index('ix_page_visits_page_name', 'page_visits', ['page_name'], unique=False)
    # ### end Alembic commands ###
