"""empty message

Revision ID: cdbc5eb765a3
Revises: 71f9514c26e6
Create Date: 2019-03-04 19:53:21.964697

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cdbc5eb765a3'
down_revision = '71f9514c26e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_details',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('send_time', sa.DateTime(), nullable=False),
                    sa.Column('unread', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_details_send_time'), 'message_details', ['send_time'], unique=False)
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('message_details_id', sa.Integer(), nullable=False),
                    sa.Column('forward', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['message_details_id'], ['message_details.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['system_users.id'], ),
                    sa.ForeignKeyConstraint(['receiver_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_forward'), 'messages', ['forward'], unique=False)
    op.create_index(op.f('ix_messages_message_details_id'), 'messages', ['message_details_id'], unique=False)
    op.create_index(op.f('ix_messages_owner_id'), 'messages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_access_tokens_expires'), 'access_tokens', ['expires'], unique=False)
    op.create_index(op.f('ix_notifications_send_time'), 'notifications', ['send_time'], unique=False)
    op.create_index(op.f('ix_system_users_last_seen'), 'system_users', ['last_seen'], unique=False)
    op.create_index(op.f('ix_system_users_system_role_id'), 'system_users', ['system_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_users_system_role_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_last_seen'), table_name='system_users')
    op.drop_index(op.f('ix_notifications_send_time'), table_name='notifications')
    op.drop_index(op.f('ix_access_tokens_expires'), table_name='access_tokens')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_owner_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_details_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_forward'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_details_send_time'), table_name='message_details')
    op.drop_table('message_details')
    # ### end Alembic commands ###
