"""empty message

Revision ID: ecb6d4718c70
Revises: 71f9514c26e6
Create Date: 2019-03-01 17:32:36.824167

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ecb6d4718c70'
down_revision = '71f9514c26e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_details',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('send_time', sa.DateTime(), nullable=False),
                    sa.Column('unread', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('message_details_id', sa.Integer(), nullable=False),
                    sa.Column('forward', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['message_details_id'], ['message_details.id'], ),
                    sa.ForeignKeyConstraint(['receiver_id'], ['system_users.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['system_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_message_details_id'), 'messages', ['message_details_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_details_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('message_details')
    # ### end Alembic commands ###
