"""empty message

Revision ID: 769ed00c4809
Revises: cdbc5eb765a3
Create Date: 2019-03-14 11:26:18.916657

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '769ed00c4809'
down_revision = 'cdbc5eb765a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('device', sa.Text(), nullable=False))
    op.add_column('access_tokens', sa.Column('last_use', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_access_tokens_last_use'), 'access_tokens', ['last_use'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tokens_last_use'), table_name='access_tokens')
    op.drop_column('access_tokens', 'last_use')
    op.drop_column('access_tokens', 'device')
    # ### end Alembic commands ###
