"""empty message

Revision ID: 58e78fda9fcc
Revises: ecb6d4718c70
Create Date: 2019-03-04 08:28:05.417507

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58e78fda9fcc'
down_revision = 'ecb6d4718c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tokens_expires'), 'access_tokens', ['expires'], unique=False)
    op.create_index(op.f('ix_message_details_send_time'), 'message_details', ['send_time'], unique=False)
    op.create_index(op.f('ix_messages_forward'), 'messages', ['forward'], unique=False)
    op.create_index(op.f('ix_notifications_send_time'), 'notifications', ['send_time'], unique=False)
    op.create_index(op.f('ix_system_users_last_seen'), 'system_users', ['last_seen'], unique=False)
    op.create_index(op.f('ix_system_users_system_role_id'), 'system_users', ['system_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_users_system_role_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_last_seen'), table_name='system_users')
    op.drop_index(op.f('ix_notifications_send_time'), table_name='notifications')
    op.drop_index(op.f('ix_messages_forward'), table_name='messages')
    op.drop_index(op.f('ix_message_details_send_time'), table_name='message_details')
    op.drop_index(op.f('ix_access_tokens_expires'), table_name='access_tokens')
    # ### end Alembic commands ###
