"""empty message

Revision ID: 2c04d7e752c7
Revises: 5b623504e9ee
Create Date: 2019-05-21 11:50:01.822581

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2c04d7e752c7'
down_revision = '5b623504e9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_visits_page_name', table_name='page_visits')
    op.drop_table('page_visits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visits',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('visits_count', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('page_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='page_visits_pkey')
                    )
    op.create_index('ix_page_visits_page_name', 'page_visits', ['page_name'], unique=True)
    # ### end Alembic commands ###
